#!/usr/bin/env python3
"""Compare IMC Marshak-wave power-law runs with different group counts.

This script compares NPZ outputs generated by:
MG_IMC/test_marshak_wave_multigroup_powerlaw.py

Expected arrays in each NPZ:
- times: (n_times,)
- r: (n_cells,)
- energy_edges: (n_groups + 1,)
- T_mat: (n_times, n_cells)
- T_rad: (n_times, n_cells)
- E_r: (n_times, n_cells)
- E_r_groups: (n_times, n_groups, n_cells)

Usage
-----
# Auto-detect IMC files in workspace root
python MG_IMC/plot_marshak_wave_multigroup_powerlaw_imc_compare.py

# Explicit file list
python MG_IMC/plot_marshak_wave_multigroup_powerlaw_imc_compare.py \
  marshak_wave_multigroup_powerlaw_imc_2g_timeBC.npz \
  marshak_wave_multigroup_powerlaw_imc_10g_timeBC.npz \
  marshak_wave_multigroup_powerlaw_imc_50g_timeBC.npz
"""

import argparse
import glob
import os
import re
import sys

import matplotlib.pyplot as plt
import numpy as np

_script_dir = os.path.dirname(os.path.abspath(__file__))
_project_root = os.path.dirname(_script_dir)
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

from utils.plotfuncs import font, show


_RUN_COLORS = ["tab:blue", "tab:red", "tab:green", "tab:purple", "tab:orange", "tab:brown"]


def _group_count(path):
    m = re.search(r"_(\d+)g", os.path.basename(path))
    return int(m.group(1)) if m else None


def _load_npz(path):
    d = np.load(path, allow_pickle=True)
    needed = ["times", "r", "energy_edges", "T_mat", "T_rad", "E_r", "E_r_groups"]
    missing = [k for k in needed if k not in d]
    if missing:
        raise KeyError(f"Missing keys in {path}: {missing}")

    out = {
        "path": path,
        "label": f"{_group_count(path)} groups" if _group_count(path) is not None else os.path.basename(path),
        "n_groups": _group_count(path),
        "times": np.asarray(d["times"], dtype=float),
        "r": np.asarray(d["r"], dtype=float),
        "energy_edges": np.asarray(d["energy_edges"], dtype=float),
        "T_mat": np.asarray(d["T_mat"], dtype=float),
        "T_rad": np.asarray(d["T_rad"], dtype=float),
        "E_r": np.asarray(d["E_r"], dtype=float),
        "E_r_groups": np.asarray(d["E_r_groups"], dtype=float),
    }
    return out


def _nearest_time_indices(ref_times, other_times, tol):
    pairs = []
    for i, t in enumerate(ref_times):
        j = int(np.argmin(np.abs(other_times - t)))
        if abs(other_times[j] - t) <= tol:
            pairs.append((i, j))
    return pairs


def _common_times(datasets, time_tol):
    # Use the dataset with the fewest snapshots as reference for robust matching.
    ref_idx = int(np.argmin([len(ds["times"]) for ds in datasets]))
    ref = datasets[ref_idx]

    valid_ref_indices = []
    for i_ref, t_ref in enumerate(ref["times"]):
        ok = True
        for k, ds in enumerate(datasets):
            if k == ref_idx:
                continue
            j = int(np.argmin(np.abs(ds["times"] - t_ref)))
            if abs(ds["times"][j] - t_ref) > time_tol:
                ok = False
                break
        if ok:
            valid_ref_indices.append(i_ref)

    if not valid_ref_indices:
        raise RuntimeError(
            f"No common times within tolerance={time_tol}. "
            f"Try increasing --time-tol."
        )

    # Build aligned index map for each dataset.
    aligned = []
    for i_ref in valid_ref_indices:
        t_ref = ref["times"][i_ref]
        row = {"time": t_ref, "indices": {ref_idx: i_ref}}
        for k, ds in enumerate(datasets):
            if k == ref_idx:
                continue
            j = int(np.argmin(np.abs(ds["times"] - t_ref)))
            row["indices"][k] = j
        aligned.append(row)

    return aligned


def _interp_profile(x_src, y_src, x_dst):
    return np.interp(x_dst, x_src, y_src)


def _parse_time_list(s):
    if s is None or s.strip() == "":
        return None
    out = []
    for tok in s.split(","):
        tok = tok.strip()
        if tok:
            out.append(float(tok))
    return out if out else None


def _plot_profiles(datasets, aligned_times, quantity_key, ylabel, outname, log_axes=False):
    n_panels = len(aligned_times)
    fig, axes = plt.subplots(1, n_panels, figsize=(4.0 * n_panels, 4.5), sharey=True)
    if n_panels == 1:
        axes = [axes]

    # Use first dataset grid as panel x-grid.
    x_ref = datasets[0]["r"]

    for ax, row in zip(axes, aligned_times):
        t_ref = row["time"]
        for ds_idx, ds in enumerate(datasets):
            i = row["indices"][ds_idx]
            y = ds[quantity_key][i]
            x = ds["r"]
            if len(x) != len(x_ref) or np.max(np.abs(x - x_ref)) > 1e-12:
                y = _interp_profile(x, y, x_ref)
                x = x_ref

            ax.plot(
                x,
                y,
                color=_RUN_COLORS[ds_idx % len(_RUN_COLORS)],
                linewidth=2,
                label=ds["label"],
            )

        if log_axes:
            ax.set_xscale("log")
            ax.set_yscale("log")
            ax.grid(True, which="both", alpha=0.25, linestyle="--")
        else:
            ax.grid(True, alpha=0.25, linestyle="--")

        ax.set_xlabel("position (cm)")
        ax.set_title(f"t = {t_ref:.2f} ns", fontsize=11)

    axes[0].set_ylabel(ylabel)
    leg = axes[-1].legend(prop=font, facecolor="white", edgecolor="none", fontsize=9)
    leg.get_frame().set_alpha(None)

    plt.tight_layout()
    show(outname, close_after=True)
    print(f"Saved: {outname}")


def _plot_spectrum_by_time_at_location(datasets, aligned_times, outbase, x_target, selected_times, time_tol):
    # Build list of rows to plot.
    if selected_times is None:
        rows = aligned_times
    else:
        rows = []
        for t_req in selected_times:
            j = int(np.argmin([abs(r["time"] - t_req) for r in aligned_times]))
            if abs(aligned_times[j]["time"] - t_req) <= time_tol:
                rows.append(aligned_times[j])

    if not rows:
        print("No spectrum times selected within tolerance; skipping spectrum plots.")
        return

    for row in rows:
        t_ref = row["time"]
        fig, ax = plt.subplots(figsize=(7.5, 5.25))

        for ds_idx, ds in enumerate(datasets):
            i_t = row["indices"][ds_idx]
            E_edges = ds["energy_edges"]
            E_mid = np.sqrt(E_edges[:-1] * E_edges[1:])
            dE = E_edges[1:] - E_edges[:-1]

            # Extract spectrum at one location (nearest cell center to x_target).
            i_x = int(np.argmin(np.abs(ds["r"] - x_target)))
            x_actual = ds["r"][i_x]
            spec = ds["E_r_groups"][i_t, :, i_x]/dE  # Convert from energy per group to spectral density

            ax.loglog(
                E_mid,
                spec,
                marker="o",
                markersize=4,
                linewidth=2,
                color=_RUN_COLORS[ds_idx % len(_RUN_COLORS)],
                label=f"{ds['label']} (x={x_actual:.3f} cm)",
            )

        ax.set_xlabel("photon energy (keV)")
        ax.set_ylabel(r"$E_{r,g}$ (GJ cm$^{-3}$ keV$^{-1}$)")
        ax.set_title(f"Spectrum at t = {t_ref:.2f} ns, x = {x_target:.3f} cm")
        ax.grid(True, which="both", alpha=0.25, linestyle="--")
        leg = ax.legend(prop=font, facecolor="white", edgecolor="none", fontsize=10)
        leg.get_frame().set_alpha(None)

        plt.tight_layout()
        outname = f"{outbase}_spectrum_t{t_ref:.2f}ns_x{x_target:.3f}cm.pdf"
        show(outname, close_after=True)
        print(f"Saved: {outname}")


def parse_args():
    p = argparse.ArgumentParser(
        description="Compare IMC Marshak-wave power-law runs for different group counts.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument(
        "files",
        nargs="*",
        help="IMC NPZ files. If omitted, auto-detect marshak_wave_multigroup_powerlaw_imc_*g*.npz in search-dir.",
    )
    p.add_argument(
        "--search-dir",
        type=str,
        default=".",
        help="Directory used for auto-detection when files are not provided.",
    )
    p.add_argument(
        "--time-tol",
        type=float,
        default=0.06,
        help="Maximum absolute time mismatch (ns) when aligning snapshots.",
    )
    p.add_argument(
        "--output-base",
        type=str,
        default="marshak_wave_multigroup_powerlaw_imc_group_compare",
        help="Prefix for output figure files.",
    )
    p.add_argument(
        "--spectrum-x",
        type=float,
        default=0.5,
        help="Spatial location (cm) where spectra E_{r,g}(x) are extracted.",
    )
    p.add_argument(
        "--spectrum-times",
        type=str,
        default="1.0,5.0",
        help="Comma-separated times (ns) for separate spectrum images; empty means all common times.",
    )
    return p.parse_args()


def main():
    args = parse_args()

    if args.files:
        paths = list(args.files)
    else:
        pattern = os.path.join(args.search_dir, "marshak_wave_multigroup_powerlaw_imc_*g*.npz")
        paths = sorted(glob.glob(pattern))

    if len(paths) < 2:
        raise RuntimeError(
            "Need at least two IMC NPZ files to compare. "
            "Pass files explicitly or generate additional group-count runs."
        )

    # Sort by group count for stable legends.
    paths = sorted(paths, key=lambda p: _group_count(p) if _group_count(p) is not None else 10**9)

    datasets = [_load_npz(p) for p in paths]

    print("Comparing IMC runs:")
    for ds in datasets:
        print(f"  {ds['label']}: {ds['path']}")

    aligned_times = _common_times(datasets, time_tol=args.time_tol)
    print("Common times used:", [f"{row['time']:.3f}" for row in aligned_times])

    _plot_profiles(
        datasets,
        aligned_times,
        quantity_key="T_mat",
        ylabel="material temperature (keV)",
        outname=f"{args.output_base}_T_mat.pdf",
        log_axes=False,
    )

    _plot_profiles(
        datasets,
        aligned_times,
        quantity_key="T_rad",
        ylabel="radiation temperature (keV)",
        outname=f"{args.output_base}_T_rad.pdf",
        log_axes=False,
    )

    _plot_profiles(
        datasets,
        aligned_times,
        quantity_key="E_r",
        ylabel=r"radiation energy (GJ/cm$^3$)",
        outname=f"{args.output_base}_E_rad_log.pdf",
        log_axes=True,
    )

    selected_times = _parse_time_list(args.spectrum_times)

    _plot_spectrum_by_time_at_location(
        datasets,
        aligned_times,
        outbase=args.output_base,
        x_target=args.spectrum_x,
        selected_times=selected_times,
        time_tol=args.time_tol,
    )


if __name__ == "__main__":
    main()
